//
// Created by loghin on 5/4/22.
//

#ifndef __MESH_LOADER_INSTANCE_CNF_H__
#define __MESH_LOADER_INSTANCE_CNF_H__

#include <meshLoader/publicTypes>

#define MESH_LOADER_DEBUG_MODE              MeshLoader_true

#define MESH_LOADER_JOB_PROGRESS_MIN_VALUE  0x00000000U
#define MESH_LOADER_JOB_PROGRESS_MAX_VALUE  0x7FFFFFFFU

#define MESH_LOADER_JOB_MEMORY_ALLOCATOR_CLEANUP_PERIOD 128U

#endif // __MESH_LOADER_INSTANCE_CNF_H__
