//
// Created by loghin on 5/4/22.
//

#ifndef __MESH_LOADER_INSTANCE_CNF_H__
#define __MESH_LOADER_INSTANCE_CNF_H__

#include <meshLoader/publicTypes>

#define MESH_LOADER_DEBUG_MODE              MeshLoader_true

#define MESH_LOADER_JOB_PROGRESS_MIN_VALUE  0x00000000U
#define MESH_LOADER_JOB_PROGRESS_MAX_VALUE  0x7FFFFFFFU

#define MESH_LOADER_JOB_MEMORY_ALLOCATOR_CLEANUP_PERIOD 128U

#define MESH_LOADER_JOB_MAXIMUM_CYCLE_COUNT             0x4000U
#define MESH_LOADER_JOB_MAXIMUM_OBJ_FILE_LENGTH         0x1000U
#define MESH_LOADER_JOB_STARTING_BUFFER_SIZE            0x40U
#define MESH_LOADER_JOB_STARTING_VERTEX_BUFFER_SIZE     MESH_LOADER_JOB_STARTING_BUFFER_SIZE
#define MESH_LOADER_JOB_STARTING_INDEX_BUFFER_SIZE      MESH_LOADER_JOB_STARTING_BUFFER_SIZE
#define MESH_LOADER_JOB_STARTING_FACE_BUFFER_SIZE       MESH_LOADER_JOB_STARTING_BUFFER_SIZE

#endif // __MESH_LOADER_INSTANCE_CNF_H__
